// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvlfnxepmlawfuwgqpno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2bGZueGVwbWxhd2Z1d2dxcG5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwMTU5MTIsImV4cCI6MjA1NDU5MTkxMn0.PvJ-PhnhAhUXUuEiORfu-KAlgkqFESSbGYeC4M5quSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);